services:
  - type: web
    name: flask-app
    env: docker
    plan: free
    repo: https://github.com/yyashhhhh1/Prometheus
    dockerfilePath: flask-app/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: prometheus-service
    env: docker
    plan: free
    repo: https://github.com/yyashhhhh1/Prometheus
    dockerfilePath: prometheus/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 9090
