global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['https://prometheus-uyp9.onrender.com/:5000']  # Replace with actual Flask service hostname
