global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    scheme: https
    static_configs:
      - targets: ['prometheus-uyp9.onrender.com']  # Replace with actual Flask service hostname
    metrics_path: '/metrics'